server:
  port: 80

spring:
  activemq:
    in-memory: true
    pool:
      enabled: false

channels:
  posts.new: ${app.channels.posts.new:newposts}
  posts.saved.success: ${app.channels.posts.save.success:postsaved}
  posts.saved.failed: ${app.channels.posts.save.failed:postsavefailed}
